apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-project
  labels:
    app: new-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-project
  template:
    metadata:
      labels:
        app: new-project
    spec:
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - containerPort: 80
