apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-project-app
  namespace: argocd
spec:
  project: devops-project
  source:
    repoURL: https://github.com/msaygin/new-project
    targetRevision: HEAD
    path: manifests/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: new-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
